all: server client listener talker

server: server.c
	cc -o server server.c

client: client.c
	cc -o client client.c

listener: listener.c
	cc -o listener listener.c

talker: talker.c
	cc -o talker talker.c
